---
- hosts: all

  handlers:
    - name: 'restart apache'
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Instala pacotes wordpress!!!'
      apt:
        name: ['php', 'apache2', 'libapache2-mod-php', 'php-gd', 'php-ssh2', 'mysql-server', 'python-mysqldb', 'php-mysql', 'python-pymysql', 'python3-pymysql']
        force_apt_get: yes
        state: latest
      become: yes

    - name: 'Cria DB do wordpress no mysql!!!'
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: wordpress_db
        login_user: root
        state: present
      become: yes

    - name: 'Cria usuario no mysql!!!'
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        name: wordpress_user
        password: '123456'
        priv: 'wordpress_db.*:ALL'
        state: present
      become: yes

    - name: 'Baixa o arquivo de instalacao do Wordpress!!!'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
        mode: 0440

    - name: 'Descompacta o wordpress!!!'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes

    - name: 'Copia wp-config-sample.php!!!'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configura os dados de acesso ao DB no wordpress!!!'
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db' }
        - { regex: 'username_here', value: 'wordpress_user' }
        - { regex: 'password_here', value: '123456' }
      become: yes

    - name: 'Configura Apache para servir o Wordpress!!!'
      copy:
        src: '/vagrant/files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
        remote_src: no
      become: yes
      notify:
        - restart apache
