---
- hosts: all
  tasks:
    - name: 'Atualiza pacotes do SO!!!'
      apt:
        name: '*'
        force_apt_get: yes
        update_cache: yes
        state: latest
      become: yes

- hosts: mysql
  roles:
    - mysql

- hosts: wordpress
  roles:
    - wordpress