---
- hosts: all
  tasks:
    - name: 'Atualiza pacotes do SO!!!'
      apt:
        name: '*'
        force_apt_get: yes
        update_cache: yes
        state: latest
      become: yes

- hosts: mysql
  handlers:
    - name: 'restart mysql'
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: 'Instala pacotes mysql!!!'
      apt:
        name: ['mysql-server', 'python-mysqldb', 'python-pymysql', 'python3-pymysql']
        force_apt_get: yes
        state: latest
      become: yes

    - name: 'Cria DB do wordpress no mysql!!!'
      mysql_db:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: "{{ wp_db_name }}"
        login_user: root
        state: present
      become: yes

    - name: 'Cria usuario no mysql!!!'
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        login_user: root
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_pass }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        host: '{{ item }}'
      become: yes
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '{{ wp_ip }}'

    - name: 'Configura mysql para acesso externo!!!'
      copy:
        src: '/vagrant/configs/files/mysqld.cnf'
        dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
        remote_src: no
      become: yes
      notify:
        - restart mysql

- hosts: wordpress
  handlers:
    - name: 'restart apache'
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Instala pacotes wordpress!!!'
      apt:
        name: ['php', 'apache2', 'libapache2-mod-php', 'php-gd', 'php-ssh2', 'php-mysql']
        force_apt_get: yes
        state: latest
      become: yes

    - name: 'Baixa o arquivo de instalacao do Wordpress!!!'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
        mode: 0440

    - name: 'Descompacta o wordpress!!!'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: /var/www/
        remote_src: yes
      become: yes

    - name: 'Copia wp-config-sample.php!!!'
      copy:
        src: "{{ wp_path }}/wp-config-sample.php"
        dest: "{{ wp_path }}/wp-config.php"
        remote_src: yes
      become: yes

    - name: 'Configura os dados de acesso ao DB no wordpress!!!'
      replace:
        path: "{{ wp_path }}/wp-config.php"
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
      with_items:
        - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
        - { regex: 'username_here', value: "{{ wp_db_user }}" }
        - { regex: 'password_here', value: "{{ wp_db_pass }}" }
        - { regex: 'localhost', value: "{{ db_ip }}" }
      become: yes

    - name: 'Configura Apache para servir o Wordpress usando template!!!'
      template:
        src: 'templates/000-default.conf.j2'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart apache
